apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ name }}-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/{{ githubOrg }}/{{ name }}.git
      targetRevision: main
      path: helm/{{ name }}
      helm:
        valueFiles:
          - $values/apps/dev/{{ name }}/values.yaml
    - repoURL: https://github.com/{{ githubOrg }}/env-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
